# Generated by Django 4.0 on 2022-01-30 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBenifit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(2000)], verbose_name='Year')),
                ('month', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(12)], verbose_name='Month')),
                ('earnings', models.FloatField(default=0, verbose_name='Earning Track')),
            ],
        ),
    ]
