# Generated by Django 4.0 on 2022-01-31 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybenifit',
            name='month',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Month'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybenifit',
            unique_together={('year', 'month')},
        ),
    ]
