# Generated by Django 4.0 on 2022-01-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='raw_qty_unit',
            field=models.CharField(default='Measurement Unit', max_length=20),
        ),
    ]
