# Generated by Django 4.0 on 2022-01-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_rawmaterial_raw_qty_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='raworder',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='raworder',
            name='amount_unit',
            field=models.CharField(default='KG', max_length=10),
        ),
        migrations.AddField(
            model_name='raworder',
            name='delivery_date',
            field=models.DateField(null=True, verbose_name='Possible Delivery Date'),
        ),
        migrations.AlterField(
            model_name='raworder',
            name='asking_price',
            field=models.FloatField(verbose_name='Asking Price Per Unit'),
        ),
    ]
