# Generated by Django 4.0 on 2022-01-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_raworder_order_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raworder',
            old_name='amount',
            new_name='quantity',
        ),
    ]
