# Generated by Django 4.0 on 2022-01-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_rename_amount_raworder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='raworder',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='raworder',
            name='order_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('Paid', 'Paid'), ('Received', 'Received')], default='New', max_length=10),
        ),
    ]
