# Generated by Django 4.0 on 2022-01-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='status',
            field=models.CharField(default='New', max_length=10, verbose_name='Issue Status'),
        ),
    ]
