# Generated by Django 4.0 on 2022-01-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_support_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.CharField(default='New', max_length=10, verbose_name='Issue Status: '),
        ),
        migrations.AlterField(
            model_name='support',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customuser', verbose_name='Issue Creator: '),
        ),
    ]
