# Generated by Django 4.0 on 2022-01-10 07:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, null=True)),
                ('product_price', models.FloatField(default=0, null=True)),
                ('product_desc', models.CharField(max_length=300, null=True)),
                ('product_qty', models.IntegerField(default=1, null=True)),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=30, null=True)),
                ('order_qty', models.IntegerField(default=1, null=True)),
                ('order_details', models.TextField()),
                ('payment_status', models.BooleanField(default=False)),
                ('order_total_price', models.FloatField(null=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30)),
                ('business_address', models.CharField(max_length=300)),
                ('business_bank_account', models.CharField(max_length=30, null=True)),
                ('business_website', models.URLField(default='https://www.', null=True)),
                ('business_email', models.EmailField(default='business_name@gmail.com', max_length=254, null=True)),
                ('business_contact_number', models.CharField(max_length=14, null=True)),
                ('business_contact_person', models.CharField(max_length=80)),
                ('business_status', models.CharField(default='National', max_length=50)),
                ('business_orders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
            ],
        ),
    ]
