# Generated by Django 4.0 on 2022-01-15 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_birthdate'),
        ('production', '0002_rawmaterial_raw_qty_unit'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_cost', models.FloatField(default=0, null=True)),
                ('delivery_cost', models.FloatField(default=0, null=True)),
                ('production_cost', models.FloatField(default=0, null=True)),
                ('others_cost', models.FloatField(default=0, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
                ('rm_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
            ],
        ),
    ]
