# Generated by Django 4.0 on 2022-01-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_order_product_creator_pricetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_creator',
            new_name='order_creator',
        ),
    ]
