# Generated by Django 4.0 on 2022-01-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_product_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_qty',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
